#ifndef EXCEPTION_H
#define EXCEPTION_H

/******************************
 * DO NOT EDIT THIS FILE
 ******************************/

class ArrayBoundsException {
	// empty class
};

class underflow {
	// empty class
};

class overflow {
	// empty class
};

class division_by_zero {
	// emtpy class
};

class illegal_argument {
	// emtpy class
};

class out_of_bounds {
	// emtpy class
};

#endif